version: "3.8"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
